spring:
  application:
    name: LearningManagementSystem
  datasource:
    url: jdbc:postgresql://localhost:5432/online_shop
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never
  logging:
    level:
      org.hibernate: ERROR
      org.hibernate.SQL: ERROR
      org.hibernate.type.descriptor.sql.BasicBinder: ERROR
  mail:
    host: smtp.gmail.com
    port: 587
    username: xturgunov069@gmail.com
    password: achj gaca mtvp vewt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

application:
  security:
    jwt:
      secret-key: 0E0864C3B7F5E51220DAE4C25DF9A3AC3F7BD65ABE229C2BA5DF7908776EB56C
      expiration: 86400000
      refresh-token:
        expiration: 604800000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true