server:
  port: 8082

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/auth/**
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/products/**

      default-filters:
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar

application:
  security:
    jwt:
      secret-key: 0E0864C3B7F5E51220DAE4C25DF9A3AC3F7BD65ABE229C2BA5DF7908776EB56C
      expiration: 86400000
