spring:
  application:
    name: OrderService
  datasource:
    url: jdbc:postgresql://dpg-d2hehrv5r7bs7380hvbg-a.oregon-postgres.render.com:5432/onlinemarket_9gd0
    username: onlinemarket_9gd0_user
    password: n4GETncwAlC2A7F5iba9XqoqyXn9TLGc
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: LaaMax
    password: 9090

server:
  port: 8081

application:
  security:
    jwt:
      secret-key: 0E0864C3B7F5E51220DAE4C25DF9A3AC3F7BD65ABE229C2BA5DF7908776EB56C
      expiration: 86400000
      refresh-token:
        expiration: 604800000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

order:
  rabbit:
    exchange: productExchange
    queue: orderProductQueue
    routing-key: productRoutingKey
